<a href="https://colab.research.google.com/github/snvssk/data240/blob/development/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import scikitplot as skplt

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
import statsmodels.api as sm
from sklearn.svm import SVR
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer
from sklearn.metrics import roc_curve, auc

In [ ]:
os.chdir('/Users/michelleyuu/Desktop/DATA240/project/data')

In [ ]:
data = pd.read_csv('weather_location_transformed.csv')
data = data.drop(columns = 'Unnamed: 0')


In [ ]:
data['outcome'] = np.where(data['GHI'] > 350, 'high',
                                 (np.where(data['GHI'] < 200, 'low', 'medium')))

In [ ]:
data = data.loc[(data['Hour'].isin([7, 10, 13, 16, 19])) & (data['Minute'] == 0)]

In [ ]:
data.head()

Year  Month  Day  Hour  Minute  Temperature  Clearsky DHI  Clearsky DNI  \
14  2020      1    1     7       0         -3.5             0             0   
20  2020      1    1    10       0          0.0            59           875   
26  2020      1    1    13       0          4.3            70           878   
32  2020      1    1    16       0          3.6            26           340   
38  2020      1    1    19       0          3.2             0             0   

    Clearsky GHI  Cloud Type  ...  Surface Albedo  Pressure  \
14             0           4  ...            0.11       987   
20           358           2  ...            0.11       986   
26           418           0  ...            0.11       982   
32            50           0  ...            0.11       980   
38             0           4  ...            0.11       980   

    Precipitable Water  Wind Direction  Wind Speed  Location ID  Latitude  \
14                 0.4           236.0         5.0       903523     41.89   
20                 0.3           205.0         6.7       903523     41.89   
26                 0.5           204.0         7.4       903523     41.89   
32                 0.7           191.0         7.3       903523     41.89   
38                 1.1           192.0         8.9       903523     41.89   

    Longitude  Elevation  outcome  
14     -87.62        179      low  
20     -87.62        179   medium  
26     -87.62        179     high  
32     -87.62        179      low  
38     -87.62        179      low  

[5 rows x 26 columns]

In [ ]:
data2 = data[['Clearsky GHI', 'Solar Zenith Angle', 'DHI', 'DNI', 'Clearsky DNI', 'Clearsky DHI', 'Cloud Type','Relative Humidity', 'Hour', 'Temperature', 'Month', 'Dew Point', 'Elevation', 'outcome']]
data2.head()

Clearsky GHI  Solar Zenith Angle  DHI  DNI  Clearsky DNI  Clearsky DHI  \
14             0               93.80    0    0             0             0   
20           358               70.01  112  414           875            59   
26           418               66.63   70  878           878            70   
32            50               86.01   28  203           340            26   
38             0              117.07    0    0             0             0   

    Cloud Type  Relative Humidity  Hour  Temperature  Month  Dew Point  \
14           4              92.20     7         -3.5      1       -4.6   
20           2              79.80    10          0.0      1       -3.1   
26           0              67.05    13          4.3      1       -1.3   
32           0              80.16    16          3.6      1        0.5   
38           4              85.80    19          3.2      1        1.1   

    Elevation outcome  
14        179     low  
20        179  medium  
26        179    high  
32        179     low  
38        179     low

In [ ]:
data.info

<bound method DataFrame.info of         Year  Month  Day  Hour  Minute  Temperature  Clearsky DHI  \
14      2020      1    1     7       0         -3.5             0   
20      2020      1    1    10       0          0.0            59   
26      2020      1    1    13       0          4.3            70   
32      2020      1    1    16       0          3.6            26   
38      2020      1    1    19       0          3.2             0   
...      ...    ...  ...   ...     ...          ...           ...   
788366  2016     12   31     7       0         -1.0             0   
788372  2016     12   31    10       0          1.0            54   
788378  2016     12   31    13       0          2.0            65   
788384  2016     12   31    16       0          0.0            17   
788390  2016     12   31    19       0         -1.0             0   

        Clearsky DNI  Clearsky GHI  Cloud Type  ...  Surface Albedo  Pressure  \
14                 0             0           4  ...       

In [ ]:
len(data['GHI'])

82125

In [ ]:
y = data2['outcome']

X = data2.drop(['outcome'], axis =1)

valid_type = ['low', 'medium', 'high']
class_le = LabelEncoder()
class_le.fit(valid_type)

y = class_le.transform(y)

#scaler = MinMaxScaler()
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
data2['outcome'].value_counts()

low       42237
high      28638
medium    11250
Name: outcome, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(57487, 13)
(24638, 13)
(57487,)
(24638,)


SVR

In [ ]:
#classifier = SVR()
#classifier.fit(X_train, y_train)

In [ ]:
classifier = SVC(kernel='rbf', decision_function_shape = 'ovr', class_weight = 'balanced', C=5, random_state=0) #class_weight = 'balanced'
classifier.fit(X_train, y_train)

SVC(C=5, class_weight='balanced', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 1 0 ... 0 0 0]


In [ ]:
cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n', cm)

Confusion matrix
 [[ 8574     0   104]
 [    0 12441   165]
 [    9     7  3338]]


In [ ]:
print('Classification Report')
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      8678
           1       1.00      0.99      0.99     12606
           2       0.93      1.00      0.96      3354

    accuracy                           0.99     24638
   macro avg       0.97      0.99      0.98     24638
weighted avg       0.99      0.99      0.99     24638



In [ ]:
f1_score(y_test, y_pred, average='weighted')

0.9886080811390278

In [ ]:
accuracy_score(y_test, y_pred)

0.9884325026382011

In [ ]:
scores = cross_val_score(classifier, X, y, cv=5)

In [ ]:
scores

array([0.98605784, 0.98575342, 0.98800609, 0.98624049, 0.98891933])

In [ ]:
y_r = data['outcome']

X_r = data.drop(['outcome', 'GHI', 'Longitude', 'Latitude'], axis =1)

valid_type = ['low', 'medium', 'high']
class_le = LabelEncoder()
class_le.fit(valid_type)

y_r = class_le.transform(y_r)

#scaler = MinMaxScaler()
scaler = StandardScaler()
X_r = scaler.fit_transform(X_r)

In [ ]:
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_r, y_r, test_size = 0.3, random_state = 0)

In [ ]:
#classifier = SVC(kernel='rbf', class_weight = 'balanced', tol = 1e-4, C=10, random_state=42)
classifier_r = SVC(kernel='rbf', decision_function_shape = 'ovr', class_weight = 'balanced', C=5, random_state=0)

classifier_r.fit(X_train_r, y_train_r)

SVC(C=5, class_weight='balanced', random_state=0)

In [ ]:
y_pred_r = classifier_r.predict(X_test_r)
print(y_pred_r)

[0 1 0 ... 0 0 0]


In [ ]:
scores = cross_val_score(classifier_r, X, y, cv=5)

scores

array([0.98605784, 0.98575342, 0.98800609, 0.98624049, 0.98891933])

In [ ]:
cm_r = confusion_matrix(y_test_r, y_pred_r)

print('Confusion matrix\n', cm_r)

Confusion matrix
 [[ 8551     0   127]
 [    0 12416   190]
 [   25    17  3312]]


In [ ]:
print('Classification Report')
print(classification_report(y_test_r, y_pred_r))

Classification Report
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      8678
           1       1.00      0.98      0.99     12606
           2       0.91      0.99      0.95      3354

    accuracy                           0.99     24638
   macro avg       0.97      0.99      0.98     24638
weighted avg       0.99      0.99      0.99     24638



In [ ]:
f1_score(y_test_r, y_pred_r, average='weighted')

0.985668664729811

In [ ]:
accuracy_score(y_test_r, y_pred_r)

0.9854290120951376

Graph for comparison 
Create dataframe where model name : feature and accuracy/F1-Score

Weather location CSV

https://www.kaggle.com/code/prashant111/logistic-regression-classifier-tutorial/notebook

Markdown